---

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    system: yes
    shell: /bin/false
    create_home: no
    state: present


- name: Download and unpack node_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Move node_exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: yes
  when: not ansible_check_mode

- name: Create textfile collector directory
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    recurse: yes

- name: Create systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart node_exporter


- name: Ensure node_exporter is enabled and running
  ansible.builtin.systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes
  when: not ansible_check_mode