- name: Create ODP directories
  file:
    path: "/data/{{ item.name }}"
    state: directory
    owner: onexodp
    group: onexodp
    mode: '0755'
  become: yes
  loop:
    - { name: 'kafka-storage', groups: ['odp-kafka'] }
    - { name: 'zookeeper-storage', groups: ['odp-zookeeper'] }
    - { name: 'doris-be-storage', groups: ['odp-doris-be'] }
    - { name: 'grafana-storage', groups: ['odp-monitoring'] }
    - { name: 'lakehouse', groups: ['odp-lakehouse'] }
  when: item.groups | intersect(group_names) | length > 0

- name: Create ODP parent
  file:
    path: "/data/ODP/tools"
    state: directory
    owner: onexodp
    group: onexodp
    mode: '0755'

- name: Create systemd user directory for onexodp on all hosts
  file:
    path: "/home/onexodp/.config/systemd/user"
    state: directory
    owner: onexodp
    group: onexodp
    mode: '0755'
  become: yes