---
- name: Bootstrap onexadmin User
  hosts: warcs
  become: yes
  remote_user: ubuntu  
  roles:
    - create-onexadmin-user

- name:
  hosts: warcs
  become: yes
  remote_user: onexadmin
  roles:
    - docker
    - system-tuning
    - disable-unattended-upgrades